### ISSUE TITLE
After some time mount disappears

### ISSUE THREAD

**Issue by Dmitry-Filippov-Rival** [freegroup/kube-s3#33]
Hi, I am using this repository as a reference in my project. I have a pod with an s3 mount running an FFMPEG microservice that reads a file from S3 and then uploads the transcoded HLS stream. On small files this works just fine, but when the files are big and take more than 5 minutes to transcode, at some point the transcoder pod fails liveness check and gets restarted, losing the transcoding progress. Do you know what the issue might be? Here are my YAML files for reference:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rival-transcoder-deployment
  labels:
    app: rival-transcoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rival-transcoder
  template:
    metadata:
      labels:
        app: rival-transcoder
    spec:
      serviceAccountName: rival-server-service-account
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: NotIn
                values:
                - infra
      containers:
        - name: rival-transcoder
          image: our trancoder image
          securityContext:
            privileged: true
          volumeMounts:
            - name: mntdatas3fs
              mountPath: /var/s3
              mountPropagation: Bidirectional
          livenessProbe:
            exec:
              command: ["ls", "/var/s3"]
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: "24Gi"
              cpu: "1"
            limits:
              memory: "24Gi"
              cpu: "4"
          ports:
          - containerPort: 1050
          imagePullPolicy: Always
          env: 
          - name: API_URL
            value: {{ .Values.api_url }}
          - name: AWS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: s3-bucket
          - name: AWS_REGION
            value: {{ .Values.aws_region }}
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: host
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: port
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
          - name: env
            value: "{{ .Values.environment }}" 
      volumes:
        - name: mntdatas3fs
          hostPath:
            path: /mnt/data-s3-fs/root
      imagePullSecrets:
      - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rival-transcoder-service
  labels:
    run: rival-transcoder
spec:
  type: ClusterIP
  selector:
    app: rival-transcoder
  ports:
    - protocol: TCP
      port: 1050
```

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3-provider
  labels:
    app: s3-provider
spec:
  selector:
    matchLabels:
      app: s3-provider
  template:
    metadata:
      labels:
        app: s3-provider
    spec:
      initContainers:
      - name: init-myservice
        image: bash
        command: ['bash', '-c', 'umount -l /mnt/data-s3-fs/root ; true']
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        envFrom:
        - secretRef:
            name: s3-credentials
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        - name: mntdatas3fs-init
          mountPath: /mnt
          mountPropagation: Bidirectional
      containers:
      - name: s3fuse
        image: ghcr.io/rival-xr/rival-s3-mount:1.0 
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","umount -f /var/s3/root"]
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        envFrom:
        - secretRef:
            name: s3-credentials
        env:
        - name: MNT_POINT
          value: /var/s3/root
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        - name: mntdatas3fs
          mountPath: /var/s3/root
          mountPropagation: Bidirectional
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: mntdatas3fs
        hostPath:
          type: DirectoryOrCreate
          path: /mnt/data-s3-fs/root
      - name: mntdatas3fs-init
        hostPath:
          type: DirectoryOrCreate
          path: /mnt
      imagePullSecrets:
      - name: ghcr-login-secret
```

Docker image is built as per instructions in this repo.
