### ISSUE TITLE
Host share on example pod is lost when s3-provider is restarted

### ISSUE THREAD

**Issue by guysoft** [freegroup/kube-s3#5]
It you set the host share to the same path as the mountpoint oh the host, if the host remounts the fuse volume, the example pod looses the folder link and gets ``Transport endpoint is not connected``

The workaround I found was to mount on the example pod a folder up the tree, and then that folder remains static and does not get a different mapping if the fuse gets remounted. That way the folder remains in place and the subfolder that mounted has its node updated correctly.

Ideally you would want something like
```
  volumes:
  - name: mntdatas3fs
    hostPath:
      path: /mnt
      subpath: data-s3-fs

```

I am not sure if that is a feature available in Kubernets. will test.
